name: supabase_demo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Remote Database
  supabase_flutter: ^2.9.1

  # SVG Package
  flutter_svg: ^2.2.0

  # Router
  go_router: ^16.0.0

  # State Management
  riverpod: ^2.6.1
  flutter_riverpod: ^2.5.1

  # Riverpod Code Gen
  riverpod_annotation:

  # Local storage
  shared_preferences: ^2.5.3

  # Class Generator
  freezed_annotation: ^3.1.0

  # Other
  json_annotation: ^4.9.0
  fpdart: ^1.1.1

  # Custom util package
  flutter_logger_plus: ^5.0.0

  # Env
  flutter_dotenv: ^5.2.1

  # Dependency Injection
  get_it: ^8.0.3

  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.5.4
  riverpod_generator:
  freezed: ^3.1.0

  json_serializable: ^6.9.5



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env
